spring.application.name=blogapi

spring.datasource.drive-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/blogapi
# Use an environment variable, fallback to 'postgres' if not set
spring.datasource.username=${DB_USERNAME:postgres}
# Use an environment variable, fallback to an empty string if not set
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Force Hibernate to map camelCase fields example (TableTitle) to snake_case columns (Table_title)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy